---
services:
  caddy:
    ports:
      - ${EUROOFFICE_PORT:-6233}:${EUROOFFICE_PORT:-6233}
  eurooffice:
    image: ghcr.io/euro-office/documentserver:latest
    restart: unless-stopped
    container_name: eurooffice
    environment:
      - JWT_ENABLED=${EUROOFFICE_JWT_ENABLED:-true}
      - JWT_SECRET=${EUROOFFICE_JWT_SECRET:?Variable is not set or empty}
    volumes:
      - /opt/onlyoffice/logs:/var/log/onlyoffice
      - /opt/onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/onlyoffice/lib:/var/lib/onlyoffice
    labels:
      caddy: ${SERVER_HOSTNAME}:${EUROOFFICE_PORT:-6233}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - frontend-net

networks:
  frontend-net:
    name: frontend-net
